book/urls.py
from django.conf.urls import url

from .views import add_view, BookListView, BookSearchResultsView


urlpatterns = [
    url(r'^$', BookListView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)$', BookListView.as_view(), name='paginator'),
    url(r'^search_results/$', BookSearchResultsView.as_view(), name='search_results'),
    url(r'^import-helper/$', add_view),
]

fdpoetrylib/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import register_view, IndexView, AccountProfileView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('book.urls', namespace='books')),
    url(r'^register/$', register_view, name='register'),
    url(r'^account/profile/$', AccountProfileView.as_view(), name='account_profile'),
]

book/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    '''图书数据模型'''

    # 索书号
    ISBN = models.CharField(max_length=50)
    # 书名
    title  = models.CharField(max_length= 100)
    # 作者
    author = models.ManyToManyField('Author')
    # 出版社
    press = models.ForeignKey('Press', blank=True, null=True, on_delete=models.SET_NULL)
    # 类别
    category = models.CharField(max_length=50)
    # 备注，允许为空
    remark = models.CharField(max_length=300, blank=True)
    # 出借状态，True为在架上，False为被借走
    state = models.BooleanField(default=True)
    # 借书人
    borrow_by = models.ForeignKey(User, blank=True, null=True)
    # 出借日期
    borrow_date = models.DateField(blank=True, null=True)
    # 应归还日期
    should_return_date = models.DateField(blank=True, null=True)
    # 豆瓣链接
    url_douban = models.URLField(blank=True)
    # 书的简介
    abstract = models.TextField(blank=True)

    def __str__(self):
        return self.title

class BorrowRecord(models.Model):
    '''图书出借记录'''
    # 出借的图书
    book = models.ForeignKey(Book)
    # 出借日期
    borrow_date = models.DateField()
    # 归还日期
    return_date = models.DateField()
    # 借书用户
    borrow_by = models.ForeignKey(User)

    def __str__(self):
        return '{}: {}'.format(self.user.username, self.book.name)

class Author(models.Model):
    '''图书作者数据模型'''

    # 作者姓名
    name = models.CharField(max_length=30)
    # 国籍
    country = models.CharField(max_length=10, blank=True)
    # 作者信息链接
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name

class Press(models.Model):
    '''出版社数据模型'''

    # 出版社名称
    name = models.CharField(max_length=50)
    # 出版社信息链接
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    '''图书评论数据模型'''

    # 评论内容
    content = models.TextField(max_length=1000)
    # 评论发表日期时间
    pub_date = models.DateTimeField(auto_now_add=True)
    # 评论的用户名
    user = models.ForeignKey(User)
    # 评论对应的书籍
    book = models.ForeignKey(Book)

    def __str__(self):
        return '{}: {}...'.format(self.user.username, self.content[:10])

# class Category(models.Model):
#     '''图书类别'''
#
#     category = models.CharField(max_length=20)
#
#     def __str__(self):
#         return self.category

templates/account_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
</head>
<body>
<h2>{{ user.username }}</h2>
<p>已借图书</p>
<ul>
{% for book in user.book_set.all %}
<li>{{ book.title }}</li>
    出借日期：{{ book.borrow_date }} &nbsp;&nbsp;
    归还日期：{{ book.should_return_date }}
{% endfor %}
</ul>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<a href="/books/">图书</a>
<a href="/account/profile/">个人中心</a>

</body>
</html>

templates/register.html
<div class='container'>
    <div class='row'>
        <div class='col-md-offset-3 col-md-6'>
            <div class='center-block'>
                {% if form.non_field_errors %}
                    <div class='alert alert-warning' role='alert'>{{ form.non_field_errors }}</div>
                {% endif %}
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <strong>注册</strong>
                    </div>
                    <div class='panel-body'>
                        <form action="{% url 'register' %}" method='post'>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class='form-group'>
                                    {{ field.label_tag }}
                                    {% if field.errors %}
                                    <span class='text-danger pull-right'>{{ field.errors }}</span>
                                    {% endif %}
                                    {{ field }}
                                    <p class='text-muted'>{{ field.help_text }}</p>
                                </div>
                            {% endfor %}
                            <button type='submit' class='btn btn-defautl'>注册</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .center-block {
        display: block;
        margin-left: auto;
        margin-right: auto;
        }

    .element {
        .center-block();
            }
</style>

templates/search_snippet.html
<form action="{% url 'books:search_results' %}" method="get">
    <select name="search_by">
        <option value="0">书名</option>
        <option value="1">作者</option>
    </select>
    <input type="text" name="search_pattern">
    <button type="submit">搜索</button>
</form>